# Generated by Django 5.1.1 on 2024-10-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images/products'),
            preserve_default=False,
        ),
    ]
